### ISSUE TITLE
Failure of Haar Cascade to detect more than one face in a single frame

### ISSUE THREAD

**Issue by NimishMishra** [iamdsc/Automated_Attendance_System#1]
I have been working on an independent project, more or less the same, that used OpenCV to connect to the webcam, draw a bounding box around the face, extract that image and save it to the directory somewhere. 

However, if there are more than two faces in the single frame (which is closer to what an automated attendance system should do), the cascade fails to recognize multiple faces.

I think for an ideal attendance system, a camera will take real-time pictures with multiple faces, extract all faces in that picture, and automatically update attendance status.

Is there a way to go about this?

**Comment by iamdsc** [comment]
I think what your code is lacking is a **_delay time_** which is required for detecting large number of faces in a frame before we read another frame from video stream, for few faces it should work normally. Try the code attached and let me know if you still face this issue.

```
import cv2
import time

face_cascade = cv2.CascadeClassifier('haarcascade_frontalface_default.xml')
cap = cv2.VideoCapture(0)
while True:
    ret, img = cap.read()
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    faces = face_cascade.detectMultiScale(gray,1.3,5)
    i=0
    for (x,y,w,h) in faces:
        cv2.rectangle(img, (x,y), (x+w, y+h), (255,0,0), 2)
        roi_color = img[y:y+h, x:x+w]
        face_file_name='faces/face_'+str(i)+'.jpg'
        cv2.imwrite(face_file_name, roi_color)
        i+=1
    cv2.imshow('image', img)
    time.sleep(1)
    k = cv2.waitKey(30) & 0xff
    if k==27:
        break
print(str(i)+' faces read')
cap.release()
cv2.destroyAllWindows()
```

**Comment by NimishMishra** [comment]
Yes it worked. Thanks.
